/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.opencadc.token;

import org.junit.Test;

import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;


public class CookieEncryptionTest {

    @Test
    public void roundTrip() throws Exception {
        final String assetKey = "ivegotabadfeelingaboutthis";
        final CookieEncrypt cookieEncrypt = new CookieEncrypt();
        final EncryptedCookie encryptedCookie = cookieEncrypt.encrypt(assetKey);

        final String marshalledCookieValue = new String(encryptedCookie.marshall(), StandardCharsets.UTF_8);
        final EncryptedCookie unmarshalledCookieValue = new EncryptedCookie(marshalledCookieValue);
        final CookieDecrypt cookieDecrypt = new CookieDecrypt();

        final String decrypted = cookieDecrypt.getAssetsKey(unmarshalledCookieValue);
        assertEquals("Wrong decrypted value.", assetKey, decrypted);
    }
}
